import type { Board } from "@/types";
import { colors } from "./theme";

const classes = [9, 10, 11, 12] as const;

export const boards: Board[] = [
  {
    id: "fbise",
    name: "Federal Board of Intermediate and Secondary Education",
    shortName: "FBISE",
    description: "Federal Board of Intermediate and Secondary Education, Islamabad",
    province: "Federal",
    classes: [...classes],
    color: colors.boards.federal,
  },
  {
    id: "bise-lahore",
    name: "Board of Intermediate and Secondary Education Lahore",
    shortName: "BISE Lahore",
    description:
      "Board of Intermediate and Secondary Education, Lahore - largest board in Punjab",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-gujranwala",
    name: "Board of Intermediate and Secondary Education Gujranwala",
    shortName: "BISE Gujranwala",
    description: "Board of Intermediate and Secondary Education, Gujranwala",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-rawalpindi",
    name: "Board of Intermediate and Secondary Education Rawalpindi",
    shortName: "BISE Rawalpindi",
    description: "Board of Intermediate and Secondary Education, Rawalpindi",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-multan",
    name: "Board of Intermediate and Secondary Education Multan",
    shortName: "BISE Multan",
    description: "Board of Intermediate and Secondary Education, Multan",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-sargodha",
    name: "Board of Intermediate and Secondary Education Sargodha",
    shortName: "BISE Sargodha",
    description: "Board of Intermediate and Secondary Education, Sargodha",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-faisalabad",
    name: "Board of Intermediate and Secondary Education Faisalabad",
    shortName: "BISE Faisalabad",
    description: "Board of Intermediate and Secondary Education, Faisalabad",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-sahiwal",
    name: "Board of Intermediate and Secondary Education Sahiwal",
    shortName: "BISE Sahiwal",
    description: "Board of Intermediate and Secondary Education, Sahiwal",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-dg-khan",
    name: "Board of Intermediate and Secondary Education DG Khan",
    shortName: "BISE DG Khan",
    description: "Board of Intermediate and Secondary Education, Dera Ghazi Khan",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-bahawalpur",
    name: "Board of Intermediate and Secondary Education Bahawalpur",
    shortName: "BISE Bahawalpur",
    description: "Board of Intermediate and Secondary Education, Bahawalpur",
    province: "Punjab",
    classes: [...classes],
    color: colors.boards.punjab,
  },
  {
    id: "bise-karachi",
    name: "Board of Intermediate Education Karachi",
    shortName: "BISE Karachi",
    description: "Board of Intermediate Education, Karachi",
    province: "Sindh",
    classes: [...classes],
    color: colors.boards.sindh,
  },
  {
    id: "bise-hyderabad",
    name: "Board of Intermediate and Secondary Education Hyderabad",
    shortName: "BISE Hyderabad",
    description: "Board of Intermediate and Secondary Education, Hyderabad",
    province: "Sindh",
    classes: [...classes],
    color: colors.boards.sindh,
  },
  {
    id: "bise-sukkur",
    name: "Board of Intermediate and Secondary Education Sukkur",
    shortName: "BISE Sukkur",
    description: "Board of Intermediate and Secondary Education, Sukkur",
    province: "Sindh",
    classes: [...classes],
    color: colors.boards.sindh,
  },
  {
    id: "bise-mirpurkhas",
    name: "Board of Intermediate and Secondary Education Mirpurkhas",
    shortName: "BISE Mirpurkhas",
    description: "Board of Intermediate and Secondary Education, Mirpurkhas",
    province: "Sindh",
    classes: [...classes],
    color: colors.boards.sindh,
  },
  {
    id: "bise-larkana",
    name: "Board of Intermediate and Secondary Education Larkana",
    shortName: "BISE Larkana",
    description: "Board of Intermediate and Secondary Education, Larkana",
    province: "Sindh",
    classes: [...classes],
    color: colors.boards.sindh,
  },
  {
    id: "bise-peshawar",
    name: "Board of Intermediate and Secondary Education Peshawar",
    shortName: "BISE Peshawar",
    description: "Board of Intermediate and Secondary Education, Peshawar",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-mardan",
    name: "Board of Intermediate and Secondary Education Mardan",
    shortName: "BISE Mardan",
    description: "Board of Intermediate and Secondary Education, Mardan",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-abbottabad",
    name: "Board of Intermediate and Secondary Education Abbottabad",
    shortName: "BISE Abbottabad",
    description: "Board of Intermediate and Secondary Education, Abbottabad",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-swat",
    name: "Board of Intermediate and Secondary Education Swat",
    shortName: "BISE Swat",
    description: "Board of Intermediate and Secondary Education, Swat",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-kohat",
    name: "Board of Intermediate and Secondary Education Kohat",
    shortName: "BISE Kohat",
    description: "Board of Intermediate and Secondary Education, Kohat",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-bannu",
    name: "Board of Intermediate and Secondary Education Bannu",
    shortName: "BISE Bannu",
    description: "Board of Intermediate and Secondary Education, Bannu",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-dera-ismail-khan",
    name: "Board of Intermediate and Secondary Education Dera Ismail Khan",
    shortName: "BISE DI Khan",
    description:
      "Board of Intermediate and Secondary Education, Dera Ismail Khan",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-malakand",
    name: "Board of Intermediate and Secondary Education Malakand",
    shortName: "BISE Malakand",
    description: "Board of Intermediate and Secondary Education, Malakand",
    province: "KPK",
    classes: [...classes],
    color: colors.boards.kpk,
  },
  {
    id: "bise-quetta",
    name: "Board of Intermediate and Secondary Education Quetta",
    shortName: "BISE Quetta",
    description: "Board of Intermediate and Secondary Education, Quetta",
    province: "Balochistan",
    classes: [...classes],
    color: colors.boards.balochistan,
  },
  {
    id: "ajk-board",
    name: "Azad Jammu and Kashmir Board of Intermediate and Secondary Education",
    shortName: "AJK Board",
    description:
      "Azad Jammu and Kashmir Board of Intermediate and Secondary Education, Mirpur",
    province: "AJK",
    classes: [...classes],
    color: colors.boards.ajk,
  },
  {
    id: "gb-board",
    name: "Gilgit-Baltistan Board of Intermediate and Secondary Education",
    shortName: "GB Board",
    description:
      "Gilgit-Baltistan Board of Intermediate and Secondary Education",
    province: "Gilgit-Baltistan",
    classes: [...classes],
    color: colors.boards.gilgitBaltistan,
  },
];

export const boardsByProvince = boards.reduce<Record<string, Board[]>>(
  (groups, board) => {
    groups[board.province] = [...(groups[board.province] ?? []), board];
    return groups;
  },
  {},
);
